[package]
name = "proc"
version = "0.1.0"
authors = ["Michael Goulet <michael@errs.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
synstructure = "0.12.4"
proc-macro2 = "1.0.21"
syn = "1.0.41"
quote = "1.0.9"
proc-macro2-diagnostics = "0.9"